os:
- linux
- osx

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then sudo apt-get install libncurses5-dev; fi
- if [[ "$TRAVIS_OS_NAME" == "linux"  ]]; then sudo apt-get install valgrind; fi

compiler:
- gcc
- clang

script:
- make all
- ./runtests.sh

language:
- c

