# Makefile template

## BEGIN Project specific variables ##

# Compiler and options #
CC=gcc
WARN=-Wall
OPT=#-O2 # no opts for now
STD=#-std=c11 # seems to be breaking the build
CFLAGS=$(WARN) $(OPT) $(STD) -g

# project sources #
EXECNAME=bugworld
INCDIR=-I include
SRCDIR=src
SRCEXT=c
OBJEXT=o
BUILDDIR=build
BINDIR=bin

# test sources #
# the directory for test suites
TESTDIR=test
# the test suite source name
TESTSRC=bugworld_test
# the object file generated by the test suite
TESTOBJ=$(BUILDDIR)/$(TESTSRC).$(OBJEXT)
# the final test exec
TESTEXEC=$(BINDIR)/$(TESTSRC)
# list of object files the test code needs to link
TESTDEPEND=$(OBJECTSNOMAIN)

# library information #
LMATH=-lm
LNCURSES=-lncurses
LDFLAGS=$(LNCURSES) $(LMATH)

# misc #
RM=rm -f

## END Project specific variables ##

# Finds all source files in the srcdir, defines list of obj files
TARGET=$(BINDIR)/$(EXECNAME)
SOURCES=$(shell find $(SRCDIR) -type f -name *.$(SRCEXT))
OBJECTS=$(patsubst $(SRCDIR)/%, $(BUILDDIR)/%, $(SOURCES:.$(SRCEXT)=.o))
OBJECTSNOMAIN=$(filter-out $(BUILDDIR)/main.$(OBJEXT), $(OBJECTS))

# Main targets
$(TARGET): $(OBJECTS)
	@echo "Linking..."
	@mkdir -p $(BINDIR)
	$(CC) $^ -o $(TARGET) $(LIB) $(LDFLAGS)

$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@echo "Building project..."
	@mkdir -p $(BUILDDIR)
	$(CC) $(CFLAGS) $(INCDIR) -c -o $@ $<

# Tests
.PHONY: test
test: $(TARGET)
	@echo "Building tests..."
	$(CC) $(CFLAGS) -c -o $(TESTOBJ) $(TESTDIR)/$(TESTSRC).$(SRCEXT) $(INCDIR) $(LDFLAGS)
	$(CC) $(CFLAGS) -o $(TESTEXEC) $(TESTDIR)/$(TESTSRC).$(SRCEXT) $(TESTDEPEND) $(INCDIR) $(LDFLAGS)

# Perform a clean and full rebuild of project and tests
all: clean $(TARGET) test

# Clean
clean:
	@echo "Cleaning...";
	$(RM) -r $(BUILDDIR) $(BINDIR)

# Run executable
run:
	@echo "Running..."
	./$(TARGET)

# Run tests
runtest:
	@echo "Running tests..."
	./$(TESTEXEC)
